doc: fix documentation error in usage section
The example provided in the documentation used a different name for g_pFuncTableInfo, whic caused compilation to fail in GPAIL_LoadApi due to an undefined symbol:

    /tmp/ccuhxdcO.o: In function `GPAIL_LoadApi(GPA_API_Type, char const*)':
    main.cpp:(.text+0x502): undefined reference to `g_pFuncTableInfo'

The documentation now includes the proper snippet taken from `include/gpu_perf_api_interface_loader.h`